name: CI

on: [push]

jobs:
    sast_scan:
        name: Run Bandit Scan 
        runs-on: ubuntu-latest

        steps: 
           - name : Checkout Code
             uses :  actions/checkout@v4.2.2

           - name : Setup Python
             uses:  actions/setup-python@v2
             with: 
                python-version: 3.8
             
           - name: Install Bandit 
             run: pip install bandit 

           - name: Bandit Scan
             run : bandit -ll -ii -r . -f json -o bandit-report.json
           - name: Upload Artifact
             uses: actions/upload-artifact@v4.6.2
             if : always ()
             with:
                name: bandit-findings
                path: bandit-report.json


   
